micronaut:
  application:
    name: esop_trading
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:5500
            - http://127.0.0.1:5500
        all:
          allowedMethods:
            - OPTIONS
            - POST
netty:
  default:
    allocator:
      max-order: 3
