name: Test Build Deploy

on:
  push:
    branches: [ "terraform" ]
  pull_request:
    branches: [ "terraform" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Test
        run: cd esop_trading && ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Build
        run: cd esop_trading && ./gradlew build

      - name: download jar file
        run: cd esop_trading && ./gradlew shadowJar


      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:

         name: esop-trading-1.0
         path: esop_trading/build/libs/esop_trading-0.1-all.jar

  terraform:
    name: "Terraform Pipeline"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.0"
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs:
      - test
      - build
      - terraform

    steps:
     - name: Setup java
       uses: actions/setup-java@v3
       with:
         distribution: corretto
         java-version: 17

     - name: Download jar file
       uses: actions/download-artifact@v3
       with:
          name: esop-trading-1.0

     - name: Copy jar file to ec2 instance
       env:
         SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
         SSH_HOST: ${{ needs.terraform.outputs.host }}
       run: |
            eval `ssh-agent`
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            ssh -T -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "fuser -k 8080/tcp"          
            scp -T -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$SSH_HOST:~
            ssh -T -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "curl -s 'https://get.sdkman.io' | bash"
            ssh -T -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "sdk install java 17.0.6-amzn"
            ssh -T -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "nohup java -jar esop-0.1-all.jar > /dev/null &"


