name: Test Build Deploy

on:
  push:
    branches: [ "terraform" ]
  pull_request:
    branches: [ "terraform" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Test
        run: ./gradlew test
      - name: Test directory
        run : pwd

